/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorIndexRouteImport } from './routes/advisor.index'
import { Route as ResultsSubmissionIdRouteImport } from './routes/results.$submissionId'
import { Route as QuestionnaireSubmissionIdRouteImport } from './routes/questionnaire.$submissionId'
import { Route as AdvisorSubmissionIdRouteImport } from './routes/advisor.$submissionId'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorIndexRoute = AdvisorIndexRouteImport.update({
  id: '/advisor/',
  path: '/advisor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsSubmissionIdRoute = ResultsSubmissionIdRouteImport.update({
  id: '/results/$submissionId',
  path: '/results/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionnaireSubmissionIdRoute =
  QuestionnaireSubmissionIdRouteImport.update({
    id: '/questionnaire/$submissionId',
    path: '/questionnaire/$submissionId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdvisorSubmissionIdRoute = AdvisorSubmissionIdRouteImport.update({
  id: '/advisor/$submissionId',
  path: '/advisor/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/advisor/$submissionId': typeof AdvisorSubmissionIdRoute
  '/questionnaire/$submissionId': typeof QuestionnaireSubmissionIdRoute
  '/results/$submissionId': typeof ResultsSubmissionIdRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/advisor/$submissionId': typeof AdvisorSubmissionIdRoute
  '/questionnaire/$submissionId': typeof QuestionnaireSubmissionIdRoute
  '/results/$submissionId': typeof ResultsSubmissionIdRoute
  '/advisor': typeof AdvisorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/advisor/$submissionId': typeof AdvisorSubmissionIdRoute
  '/questionnaire/$submissionId': typeof QuestionnaireSubmissionIdRoute
  '/results/$submissionId': typeof ResultsSubmissionIdRoute
  '/advisor/': typeof AdvisorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/submissions'
    | '/advisor/$submissionId'
    | '/questionnaire/$submissionId'
    | '/results/$submissionId'
    | '/advisor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/submissions'
    | '/advisor/$submissionId'
    | '/questionnaire/$submissionId'
    | '/results/$submissionId'
    | '/advisor'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/submissions'
    | '/advisor/$submissionId'
    | '/questionnaire/$submissionId'
    | '/results/$submissionId'
    | '/advisor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdvisorSubmissionIdRoute: typeof AdvisorSubmissionIdRoute
  QuestionnaireSubmissionIdRoute: typeof QuestionnaireSubmissionIdRoute
  ResultsSubmissionIdRoute: typeof ResultsSubmissionIdRoute
  AdvisorIndexRoute: typeof AdvisorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/': {
      id: '/advisor/'
      path: '/advisor'
      fullPath: '/advisor/'
      preLoaderRoute: typeof AdvisorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$submissionId': {
      id: '/results/$submissionId'
      path: '/results/$submissionId'
      fullPath: '/results/$submissionId'
      preLoaderRoute: typeof ResultsSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/questionnaire/$submissionId': {
      id: '/questionnaire/$submissionId'
      path: '/questionnaire/$submissionId'
      fullPath: '/questionnaire/$submissionId'
      preLoaderRoute: typeof QuestionnaireSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor/$submissionId': {
      id: '/advisor/$submissionId'
      path: '/advisor/$submissionId'
      fullPath: '/advisor/$submissionId'
      preLoaderRoute: typeof AdvisorSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdvisorSubmissionIdRoute: AdvisorSubmissionIdRoute,
  QuestionnaireSubmissionIdRoute: QuestionnaireSubmissionIdRoute,
  ResultsSubmissionIdRoute: ResultsSubmissionIdRoute,
  AdvisorIndexRoute: AdvisorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
